version: '3.4'
services:
  webapp:
    image: frolvlad/alpine-glibc:alpine-3.12
    container_name: like_the_certain_board
    build:
      context: ./docker/webapp
      dockerfile: Dockerfile
      network: host
    # tty: true
    restart: "no"
    entrypoint: "/root/.roswell/local-projects/like-the-certain-board/dockerRun.sh"
    depends_on:
      - db
    expose:
      - 8888
    volumes:
      - ./:/root/.roswell/local-projects/like-the-certain-board/
      - ../dat/:/roswell/dat/
      - ../html/:/roswell/html/
      - ../settings/:/roswell/settings/

  db:
    image: mysql:latest
    container_name: mysql_docker
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: mysite
      MYSQL_USER: lain
      MYSQL_PASSWORD: user_pass
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf:/etc/mysql/conf.d
      - ./docker/mysql/log:/var/log/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_on_docker
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - webapp
    ports:
      - 8080:80
      - 8081:443

